my_string =input()
print(my_string.upper())
my_string =input()
print(my_string.lower())
print("Я студент университета Urban".replace(' ', '#'))
my_string =input()
print(my_string[0])
my_string =input()
print(my_string[-1])